catalog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^books/$', views.BookListView.as_view(), name='books'),
	url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
	url(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
	url(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
	url(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
	url(r'^borrowed-books/$', views.LoanedBooksListView.as_view(), name='borrowed-books'),
	url(r'^book/(?P<pk>[-\w]+)/renew/$', views.renew_book, name='renew-book'),
	url(r'^author/create/$', views.AuthorCreate.as_view(), name='author_create'),
	url(r'^author/(?P<pk>\d+)/update/$', views.AuthorUpdate.as_view(), name='author_update'),
	url(r'^author/(?P<pk>\d+)/delete/$', views.AuthorDelete.as_view(), name='author_delete'),
	url(r'^book/create/$', views.BookCreate.as_view(), name='book_create'),
	url(r'^book/(?P<pk>\d+)/update/$', views.BookUpdate.as_view(), name='book_update'),
	url(r'^book/(?P<pk>\d+)/delete/$', views.BookDelete.as_view(), name='book_delete'),
]

locallibrary/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^$', RedirectView.as_view(url='/catalog/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
import uuid # Required for unique book instances
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User
from datetime import date

class Genre(models.Model):
	"""
	Model representing a book genre (e.g. Science Fiction, Non Fiction).
	"""
	name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")

	def __str__(self):
		"""
		String for representing the Model object (in Admin site etc.)
		"""
		return self.name

class Language(models.Model):
	"""
	Model representing a Language (e.g. English, French, Japanese, etc.)
	"""
	name = models.CharField(max_length=200, help_text="Enter a the book's natural language (e.g. English, French, Japanese etc.)")

	def __str__(self):
		"""
		String for representing the Model object (in Admin site etc.)
		"""
		return self.name

class Book(models.Model):
	"""
	Model representing a book (but not a specific copy of a book).
	"""
	title = models.CharField(max_length=200)
	author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
	# Foreign Key used because book can only have one author, but authors can have multiple books
	# Author as a string rather than object because it hasn't been declared yet in the file.
	summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
	isbn = models.CharField('ISBN',max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
	genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
	# ManyToManyField used because genre can contain many books. Books can cover many genres.
	# Genre class has already been defined so we can specify the object above.
	language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

	class Meta:
		ordering = ["title"]

	def __str__(self):
		"""
		String for representing the Model object.
		"""
		return self.title


	def get_absolute_url(self):
		"""
		Returns the url to access a particular book instance.
		"""
		return reverse('book-detail', args=[str(self.id)])

	def display_genre(self):
		"""
		Creates a string for the Genre. This is required to display genre in Admin.
		"""
		return ', '.join([ genre.name for genre in self.genre.all()[:3] ])
	display_genre.short_description = 'Genre'

class BookInstance(models.Model):
	"""
	Model representing a specific copy of a book (i.e. that can be borrowed from the library).
	"""
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
	book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True) 
	imprint = models.CharField(max_length=200)
	borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
	due_back = models.DateField(null=True, blank=True)

	LOAN_STATUS = (
		('m', 'Maintenance'),
		('o', 'On loan'),
		('a', 'Available'),
		('r', 'Reserved'),
	)

	status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

	class Meta:
		ordering = ["due_back"]
		permissions = (("can_mark_returned", "Set book as returned"),)

	@property
	def is_overdue(self):
		if self.due_back and date.today() > self.due_back:
			return True
		return False

	def __str__(self):
		"""
		String for representing the Model object
		"""
		return '%s (%s)' % (self.id,self.book.title)

class Author(models.Model):
	"""
	Model representing an author.
	"""
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	date_of_birth = models.DateField(null=True, blank=True)
	date_of_death = models.DateField('Died', null=True, blank=True)

	def get_absolute_url(self):
		"""
		Returns the url to access a particular author instance.
		"""
		return reverse('author-detail', args=[str(self.id)])

	class Meta:
		ordering = ["last_name"]

	def __str__(self):
		"""
		String for representing the Model object.
		"""
		return '%s, %s' % (self.last_name, self.first_name)

catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime #for checking renewal date range.

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        #Check date is not in past. 
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        #Check date is in range librarian allowed to change (+4 weeks).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

catalog/views.py
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render
from django.views import generic
from .models import Book, Author, BookInstance, Genre
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin

from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
import datetime

from .forms import RenewBookForm

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

def index(request):
	"""
	View function for home page of site.
	"""
	# Number of visits to this view, as counted in the session variable.
	num_visits = request.session.get('num_visits', 0)
	request.session['num_visits'] = num_visits+1
	# Generate counts of some of the main objects
	num_books = Book.objects.all().count()
	num_instances = BookInstance.objects.all().count()
	# Available books (status = 'a')
	num_instances_available = BookInstance.objects.filter(status__exact='a').count()
	num_authors = Author.objects.count()  # The 'all()' is implied by default.

	num_genres = Genre.objects.all().count()

	num_books_fiction 	= Book.objects.filter(genre__name__contains='fiction').count()
	num_books_mythology = Book.objects.filter(genre__name__contains='mythological').count()

	# Render the HTML template index.html with the data in the context variable
	return render(
		request,
		'index.html',
		context={
			'num_books':num_books,
			'num_instances':num_instances,
			'num_instances_available':num_instances_available,
			'num_authors':num_authors,
			'num_genres':num_genres,
			'num_books_fiction':num_books_fiction,
			'num_books_mythology':num_books_mythology,
			'num_visits':num_visits
		},
	)

class BookListView(generic.ListView):
	model = Book
	template_name = 'books/book_list.html'
	paginate_by = 2

class BookDetailView(generic.DetailView):
	model = Book

	template_name = 'books/book_detail.html'

	def book_detail_view(request,pk):
		try:
			book_id = Book.objects.get(pk=pk)
		except Book.DoesNotExist:
			raise Http404("Book Does not exist")

		return render(
			request,
			'catalog/book_detail.html',
			context={'book':book_id,}
		)

class AuthorListView(generic.ListView):
	model = Author
	template_name = 'authors/author_list.html'
	paginate_by = 2

class AuthorDetailView(generic.DetailView):
	model = Author

	template_name = 'authors/author_detail.html'

	def get_context_data(self, **kwargs):
		# Call the base implementation first to get a context
		context = super(AuthorDetailView, self).get_context_data(**kwargs)
		# Get the blog from id and add it to the context
		context['books'] = Book.objects.all()
		return context

	def author_detail_view(request,pk):
		try:
			author_id = Author.objects.get(pk=pk)
		except Author.DoesNotExist:
			raise Http404("Author Does not exist")

		return render(
			request,
			'catalog/author_detail.html',
			context={'author':author_id, }
		)

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
	"""
	Generic class-based view listing books on loan to current user. 
	"""
	model = BookInstance
	template_name ='books/bookinstance_list_borrowed_user.html'
	paginate_by = 2

	def get_queryset(self):
		return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')



class LoanedBooksListView(PermissionRequiredMixin,generic.ListView):
	"""
	Generic class-based view listing books on loan to current user. 
	"""
	permission_required = 'catalog.can_mark_returned'
	model = BookInstance
	template_name ='books/bookinstance_list_borrowed.html'
	paginate_by = 2

	def get_queryset(self):
		return BookInstance.objects.filter(status__exact='o').order_by('due_back')

@permission_required('catalog.can_mark_returned')
def renew_book(request, pk):
	book_inst=get_object_or_404(BookInstance, pk = pk)

	# If this is a POST request then process the Form data
	if request.method == 'POST':

		# Create a form instance and populate it with data from the request (binding):
		form = RenewBookForm(request.POST)

		# Check if the form is valid:
		if form.is_valid():
			# process the data in form.cleaned_data as required (here we just write it to the model due_back field)
			book_inst.due_back = form.cleaned_data['renewal_date']
			book_inst.save()

			# redirect to a new URL:
			return HttpResponseRedirect(reverse('borrowed-books') )

	# If this is a GET (or any other method) create the default form.
	else:
		proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
		form = RenewBookForm(initial={'renewal_date': proposed_renewal_date,})

	return render(request, 'books/book_renew.html', {'form': form, 'bookinst':book_inst})

class AuthorCreate(PermissionRequiredMixin,CreateView):
	permission_required = 'catalog.can_mark_returned'
	model = Author
	template_name ='authors/author_form.html'
	fields = '__all__'
	initial={'date_of_death':'12/10/2016',}

class AuthorUpdate(PermissionRequiredMixin,UpdateView):
	permission_required = 'catalog.can_mark_returned'
	model = Author
	template_name ='authors/author_form.html'
	fields = ['first_name','last_name','date_of_birth','date_of_death']

class AuthorDelete(PermissionRequiredMixin,DeleteView):
	permission_required = 'catalog.can_mark_returned'
	model = Author
	template_name ='authors/author_confirm_delete.html'
	success_url = reverse_lazy('authors')

class BookCreate(PermissionRequiredMixin,CreateView):
	permission_required = 'catalog.can_mark_returned'
	model = Book
	template_name ='books/book_form.html'
	fields = '__all__'

class BookUpdate(PermissionRequiredMixin,UpdateView):
	permission_required = 'catalog.can_mark_returned'
	model = Book
	template_name ='books/book_form.html'
	fields = '__all__'

class BookDelete(PermissionRequiredMixin,DeleteView):
	permission_required = 'catalog.can_mark_returned'
	model = Book
	template_name ='books/book_confirm_delete.html'
	success_url = reverse_lazy('books')

catalog/templates/books/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/books/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong><a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/books/book_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

catalog/templates/books/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
         - <a href="{{ book.get_absolute_url }}/update/">Edit</a>
         - <a href="{{ book.get_absolute_url }}/delete/">Delete</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}       
{% endblock %}

catalog/templates/books/book_renew.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

catalog/templates/books/bookinstance_list_borrowed.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}) - {{ bookinst.borrower }} 
        {% if perms.catalog.can_mark_returned %} - <a href="{% url 'renew-book' bookinst.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/books/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}